// <auto-generated />
using System;
using EAV.api.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EAV.api.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "attribute_value_type", new[] { "text", "integer", "decimal", "boolean", "date", "custom_object" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EAV.api.Entities.EAV.CustomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("CustomEntities", (string)null);
                });

            modelBuilder.Entity("EAV.api.Entities.EAV.CustomEntity", b =>
                {
                    b.OwnsMany("EAV.api.Entities.EAV.ValueObjects.CustomAttribute", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CustomEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ValueType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("CustomEntityId");

                            b1.ToTable("CustomAttributes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomEntityId");

                            b1.OwnsMany("EAV.api.Entities.EAV.ValueObjects.CustomValue", "Values", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("CustomAttributeId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("ValueData")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("Id");

                                    b2.HasIndex("CustomAttributeId");

                                    b2.ToTable("CustomValues", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CustomAttributeId");
                                });

                            b1.Navigation("Values");
                        });

                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
