version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: eavusr
      POSTGRES_PASSWORD: eavpassword
      POSTGRES_DB: eav_database
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
